/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type BusinessCategory = "automotive" | "education" | "finance" | "healthcare" | "hospitality" | "other" | "real_estate" | "restaurant" | "retail" | "technology";

export type BusinessStatus = "approved" | "pending" | "rejected";

export type ClaimAuditAction = "admin_note_added" | "claim_approved" | "claim_rejected" | "claim_submitted" | "document_uploaded" | "status_changed";

export type ClaimVerificationStatus = "pending" | "rejected" | "under_review" | "verified";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type ListingSource = "community" | "owner";

export type NotificationType = "bad_review" | "claim_approved" | "claim_rejected" | "claim_submitted" | "new_review";

export type Numeric = ColumnType<string, number | string, number | string>;

export type OwnershipStatus = "claimed" | "unclaimed" | "verified";

export type ProofType = "business_registration" | "domain_ownership" | "email_verification" | "payment_processor" | "platform_admin" | "signed_declaration" | "tax_id";

export type ReviewSentiment = "mixed" | "negative" | "neutral" | "positive";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type UserRole = "admin" | "user";

export type VerificationTier = "basic_verified" | "community_listed" | "trusted_verified";

export type VisibilityStatus = "hidden" | "pending_review" | "published";

export interface BusinessClaims {
  adminNotes: string | null;
  businessId: number;
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  ownerEmail: string;
  ownerName: string;
  proofDescription: string;
  proofType: ProofType;
  updatedAt: Generated<Timestamp>;
  userId: number;
  verificationStatus: Generated<ClaimVerificationStatus>;
}

export interface Businesses {
  addedByUserId: number | null;
  averageRating: Generated<Numeric | null>;
  category: Generated<BusinessCategory>;
  claimedByUserId: number | null;
  contactEmail: string | null;
  createdAt: Generated<Timestamp>;
  description: string | null;
  id: Generated<number>;
  isClaimed: Generated<boolean>;
  listingSource: Generated<ListingSource>;
  location: string | null;
  name: string;
  ownershipStatus: Generated<OwnershipStatus>;
  phone: string | null;
  status: Generated<BusinessStatus>;
  totalReviews: Generated<number | null>;
  updatedAt: Generated<Timestamp>;
  verificationTier: Generated<VerificationTier>;
  visibilityStatus: Generated<VisibilityStatus>;
  website: string | null;
}

export interface ClaimAuditLog {
  action: ClaimAuditAction;
  actorId: number;
  claimId: number;
  createdAt: Generated<Timestamp>;
  details: string | null;
  id: Generated<number>;
  newValue: string | null;
  oldValue: string | null;
}

export interface ClaimDocuments {
  claimId: number;
  createdAt: Generated<Timestamp>;
  fileName: string;
  fileSize: number;
  fileType: string;
  id: Generated<number>;
  storagePath: string;
}

export interface LoginAttempts {
  attemptedAt: Generated<Timestamp | null>;
  email: string;
  id: Generated<number>;
  success: Generated<boolean>;
}

export interface Notifications {
  businessId: number;
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  isRead: Generated<boolean>;
  message: string;
  reviewId: number | null;
  type: Generated<NotificationType>;
  userId: number;
}

export interface OauthAccounts {
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  provider: string;
  providerEmail: string | null;
  providerUserId: string;
  updatedAt: Generated<Timestamp>;
  userId: number;
}

export interface OauthStates {
  codeVerifier: Generated<string>;
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: Generated<number>;
  provider: string;
  redirectUrl: string;
  state: string;
}

export interface Reviews {
  businessId: number;
  content: string;
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  rating: number;
  reviewerName: Generated<string>;
  sentiment: Generated<ReviewSentiment | null>;
}

export interface Sessions {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  lastAccessed: Generated<Timestamp>;
  userId: number;
}

export interface UserPasswords {
  passwordHash: string;
  userId: number;
}

export interface Users {
  avatarUrl: string | null;
  createdAt: Generated<Timestamp>;
  displayName: string;
  email: string;
  id: Generated<number>;
  role: Generated<UserRole>;
  updatedAt: Generated<Timestamp>;
}

export interface DB {
  businessClaims: BusinessClaims;
  businesses: Businesses;
  claimAuditLog: ClaimAuditLog;
  claimDocuments: ClaimDocuments;
  loginAttempts: LoginAttempts;
  notifications: Notifications;
  oauthAccounts: OauthAccounts;
  oauthStates: OauthStates;
  reviews: Reviews;
  sessions: Sessions;
  userPasswords: UserPasswords;
  users: Users;
}


// Use these for zod schema enums or other purposes, since the kysely enums are just types
export const ReviewSentimentArrayValues: [ReviewSentiment, ...ReviewSentiment[]] = ["mixed","negative","neutral","positive"];
export const BusinessCategoryArrayValues: [BusinessCategory, ...BusinessCategory[]] = ["automotive","education","finance","healthcare","hospitality","other","real_estate","restaurant","retail","technology"];
export const UserRoleArrayValues: [UserRole, ...UserRole[]] = ["admin","user"];
export const NotificationTypeArrayValues: [NotificationType, ...NotificationType[]] = ["bad_review","claim_approved","claim_rejected","claim_submitted","new_review"];
export const BusinessStatusArrayValues: [BusinessStatus, ...BusinessStatus[]] = ["approved","pending","rejected"];
export const ProofTypeArrayValues: [ProofType, ...ProofType[]] = ["business_registration","domain_ownership","email_verification","payment_processor","platform_admin","signed_declaration","tax_id"];
export const ClaimVerificationStatusArrayValues: [ClaimVerificationStatus, ...ClaimVerificationStatus[]] = ["pending","rejected","under_review","verified"];
export const ClaimAuditActionArrayValues: [ClaimAuditAction, ...ClaimAuditAction[]] = ["admin_note_added","claim_approved","claim_rejected","claim_submitted","document_uploaded","status_changed"];
export const VisibilityStatusArrayValues: [VisibilityStatus, ...VisibilityStatus[]] = ["hidden","pending_review","published"];
export const OwnershipStatusArrayValues: [OwnershipStatus, ...OwnershipStatus[]] = ["claimed","unclaimed","verified"];
export const VerificationTierArrayValues: [VerificationTier, ...VerificationTier[]] = ["basic_verified","community_listed","trusted_verified"];
export const ListingSourceArrayValues: [ListingSource, ...ListingSource[]] = ["community","owner"];
// Note: kysely maps the table/column/enum names from snake_case to camelCase and PascalCase. When running SQL statements, make sure to use snake_case, but TypeScript code should use camelCase or PascalCase.